### ISSUE TITLE
bootstrap=True

### ISSUE THREAD

**Issue by Olecranon** [GoogleCloudPlatform/plspm-python#1]
Hi there.

Thanks for the plspm package.
There might be a bug to set bootstrap=True
I put this argument in your example, only the first example can get through. The rest all have the error...

`
~\AppData\Local\conda\conda\envs\py36\lib\site-packages\pandas\core\indexing.py in error()
   1783                 raise KeyError(u"the label [{key}] is not in the [{axis}]"
   1784                                .format(key=key,
-> 1785                                        axis=self.obj._get_axis_name(axis)))
   1786 
   1787             try:
KeyError: 'the label [weights] is not in the [columns]'
`

**Comment by jezhumble** [comment]
Thanks for the report. Fixed in 0.4.2.
