### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'append'

### ISSUE THREAD

**Issue by lessapwb** [GoogleCloudPlatform/plspm-python#11]
I am still with the same problem, I can't run the code because it give me the AtributeError. I use the exactly code that is available on plspm library. Someone could help me?

`#!/usr/bin/env python3
import pandas as pd, plspm.config as c
from plspm.plspm import Plspm
from plspm.scheme import Scheme
from plspm.mode import Mode

satisfaction = pd.read_csv("satisfaction.csv", index_col=0)

structure = c.Structure()
structure.add_path(["IMAG"], ["EXPE", "SAT", "LOY"])
structure.add_path(["EXPE"], ["QUAL", "VAL", "SAT"])
structure.add_path(["QUAL"], ["VAL", "SAT"])
structure.add_path(["VAL"], ["SAT"])
structure.add_path(["SAT"], ["LOY"])

config = c.Config(structure.path(), scaled=False)
config.add_lv_with_columns_named("IMAG", Mode.A, satisfaction, "imag")
config.add_lv_with_columns_named("EXPE", Mode.A, satisfaction, "expe")
config.add_lv_with_columns_named("QUAL", Mode.A, satisfaction, "qual")
config.add_lv_with_columns_named("VAL", Mode.A, satisfaction, "val")
config.add_lv_with_columns_named("SAT", Mode.A, satisfaction, "sat")
config.add_lv_with_columns_named("LOY", Mode.A, satisfaction, "loy")

plspm_calc = Plspm(satisfaction, config, Scheme.CENTROID)
print(plspm_calc.inner_summary())
print(plspm_calc.path_coefficients())`

![image](https://github.com/GoogleCloudPlatform/plspm-python/assets/92831098/98675616-4bc1-4022-8a1b-f0ed89a98e62)
![image](https://github.com/GoogleCloudPlatform/plspm-python/assets/92831098/57c54659-a4d0-41e7-9310-4d09551484aa)
![image](https://github.com/GoogleCloudPlatform/plspm-python/assets/92831098/cca48ce4-aa1d-4c1c-8d7b-0543498637c6)

**Comment by lessapwb** [comment]
I could resolve the problem using Google Colab. But I would like to know why, if someone know, please, tell me haha

**Comment by TitoTFP** [comment]
Yes, i got the same issues

**Comment by TitoTFP** [comment]
> Yes, i got the same issues

Ohh, i think it's because the updated pandas version

**Comment by lessapwb** [comment]
@TitoTFP  Could you tell what version are you trying to use?

**Comment by TitoTFP** [comment]
> @TitoTFP Can you tell what version you are trying to use?

I'm using pandas version 2.0.3 for my jupyter notebook. But then I realised that google collab uses pandas version 1.5.3. Then I tried it, and it worked.

**Comment by lessapwb** [comment]
OMG! You're a genius. Thank you, a lot!!!

**Comment by jezhumble** [comment]
Thanks and sorry for not following up earlier, it looks like the `append` method was removed in pandas 2.0: https://stackoverflow.com/questions/75956209/error-dataframe-object-has-no-attribute-append. I will fix it and make a new release this week.

**Comment by skon7** [comment]
The issue was caused by a compatibility problem with pandas versions greater than 2. : [stackoverflow](https://stackoverflow.com/questions/75956209/error-dataframe-object-has-no-attribute-append#answer-75956237)

**Comment by FengMind** [comment]
Uninstall the current version of pandas and reinstall 1.5.2 (conda install pandas==1.5.2).

**Comment by jezhumble** [comment]
The latest 0.5.7 release incorporates @jhorzek's fixes and my fix and we now support pandas 2.0+ and numpy 2.0+. Thanks Jannik!
