### ISSUE TITLE
Documentation example in readthedocs.io is wrong

### ISSUE THREAD

**Issue by LWackerle** [GoogleCloudPlatform/plspm-python#9]
The example code (in image below) contains the Structure attribute .addPath. The correct attribute is .add_path. 

![image](https://user-images.githubusercontent.com/50578103/133988518-86e0fba5-6b68-4068-bd4c-edca7028dd9b.png)

**Comment by LWackerle** [comment]
Error is throughout the whole documentation it seems:

![image](https://user-images.githubusercontent.com/50578103/133990134-a055e450-b3bf-46b7-99cc-a35de1940cd4.png)

**Comment by jezhumble** [comment]
Updated now! Thanks for letting me know!
